name: Auto Assignees

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-auto-assignees:
    runs-on: ubuntu-latest

    steps:
      - name: add assignees
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/mash-up-kr/Dorabangs_Android/issues/${{ github.event.number }}/assignees \
            -d '{"assignees": ${{ github.actor }} }'
